### ISSUE TITLE
how to generate one-to-one matching result

### ISSUE THREAD

**Issue by BotMichael** [ChuXiaokai/CrossMNA#1]
Hi Xiaokai, I'm very interested in your MNA algorithm and I'm currently experimenting with it. However, I'm not sure how to get the multiple network alignment result using the inter-vectors. Would you please give me a hint(or a helper script if possible) about how to generate the alignment result from them? Best!

**Comment by ChuXiaokai** [comment]
Sorry to reply so late.
For fair comparison,  we just calculate the similarities of inter-vectors between a test node and all candidates in another network, and then find the top@n most similar nodes.
If you want to adopt one-to-one constraint into embedding-based multi-network alignment, I think the matching strategy in this work "Inferring Anchor Links across Multiple Heterogeneous Social Networks" may help you.

**Comment by ChuXiaokai** [comment]
> Hi Xiaokai, I'm very interested in your MNA algorithm and I'm currently experimenting with it. However, I'm not sure how to get the multiple network alignment result using the inter-vectors. Would you please give me a hint(or a helper script if possible) about how to generate the alignment result from them? Best!

Sorry to reply so late.
For fair comparison, we just calculate the similarities of inter-vectors between a test node and all candidates in another network, and then find the top@n most similar nodes.
If you want to adopt one-to-one constraint into embedding-based multi-network alignment, I think the matching strategy in this work "Inferring Anchor Links across Multiple Heterogeneous Social Networks" may help you.

**Comment by BotMichael** [comment]
Thx
