### ISSUE TITLE
运行main.py 报错ValueError: Cannot feed value of shape (1024,) for Tensor u'u_i:0', which has shape '(3072,)'

### ISSUE THREAD

**Issue by arron7856d** [ChuXiaokai/CrossMNA#2]
环境python==2.7 tensorflow ==1.4
使用的是自带的数据集，报错信息如下：
`('arXiv', '0.1', 'NetworkAlignment')`
`epoch 0: time for generate batches=2.231533s
Traceback (most recent call last):`
  `File "main.py", line 75, in <module>
    _, loss = sess.run([train_op, model.loss], feed_dict=feed_dict)`
  `File "/home/zk/anaconda3/envs/alp-crossmna/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run`
    `run_metadata_ptr)`
 ` File "/home/zk/anaconda3/envs/alp-crossmna/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1096, in _run`
    `% (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))`
`ValueError: Cannot feed value of shape (1024,) for Tensor u'u_i:0', which has shape '(3072,)'`
请问这个问题怎么解决？

**Comment by ChuXiaokai** [comment]
不好意思 已修正 你重新pull一下
