### ISSUE TITLE
Usage of intra-vector for node classification task? 

### ISSUE THREAD

**Issue by siri-ius** [ChuXiaokai/CrossMNA#3]
Hi,

I would like to know if the intra-vector could be used for the node classification task? If yes, how? 

Thank you!

**Comment by ChuXiaokai** [comment]
> cl

Sorry for my late reply. 
We did not use intra-vector for node classification task before, you can have a try. 
But in my point of view, I think inter-vector is more suitable for multi-layer node classification task than intra-vector.
